name: Metrics

on:
  # Update every 12 hours
  schedule: [{cron: "0 */12 * * *"}]
  # Allow manual update
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub username
          user: jawad114
          token: ${{ secrets.METRICS_TOKEN }}

          # Template
          template: classic

          # Sections
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 10
          plugin_stars: yes
          plugin_followup: yes
          plugin_repositories: yes
          plugin_achievements: yes

          # Config
          config_timezone: Asia/Karachi
